# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      AppBundle\Entity\User:
                  algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
              class: AppBundle:User
              property: username


    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                      login_path: login
                      check_path: login


    access_control:
    - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN] }
    - { path: ^/admin, roles: ROLE_ADMIN }